baseurl: /grainy_black

title: "Harsh Patel"
author: "Harsh Patel"
about: "Computer Programmer"
describe: "I have a fervid Motto Of Making Any Task Easier By Programming; Always Trying to Whet My Programming Skills; Never Reposing ; Fully Germane to Computer Science."
contact: "9978779967"
email: "harshgp44@gmail.com"
facebook: ""
twitter: ""
insta: ""
github: ""